### ISSUE TITLE
feat: Add scheduler

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk-java#5]
Similar to https://github.com/cloudquery/plugin-sdk/blob/0c475702592506e2fce708384dd2bd5c8b9da827/scheduler/scheduler.go
```[tasklist]
### Tasks
- [ ] Implement Concurrency
- [ ] Handle nested tables (relations)
- [x] ~~Add a default object path resolver based on column name~~ Already implemented via table transformer
- [x] Implement encoding of resources to arrow records
```
