### ISSUE TITLE
chore: add implementations for arrow extension types

### ISSUE THREAD

**Issue by mnorbury** [cloudquery/plugin-sdk-java#50]
```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/plugin-sdk-java/issues/72
- [ ] https://github.com/cloudquery/plugin-sdk-java/issues/73
- [ ] https://github.com/cloudquery/plugin-sdk-java/issues/74
- [ ] https://github.com/cloudquery/plugin-sdk-java/issues/57
```

**Comment by erezrokah** [comment]
Closing as done for the initial version
